name: Build TulipCC Firmware (TDECK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up ESP-IDF
      uses: espressif/setup-idf@v1
      with:
        esp_idf_version: v5.4.1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython littlefs-python

    - name: Build TDECK firmware
      run: |
        cd tulip/esp32s3
        idf.py -DMICROPY_BOARD=TDECK build

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      with:
        name: tulipcc-tdeck-firmware
        path: tulip/esp32s3/build/*.bin
