name: Build TulipCC Firmware (TDECK)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install -y git wget flex bison gperf python3 python3-pip cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        pip3 install cython littlefs-python

    - name: Install ESP-IDF
      run: |
        mkdir -p ~/esp
        cd ~/esp
        git clone -b v5.4.1 --recursive https://github.com/espressif/esp-idf.git esp-idf-v5.4.1
        cd esp-idf-v5.4.1
        ./install.sh esp32s3
        echo "source ~/esp/esp-idf-v5.4.1/export.sh" >> $GITHUB_ENV

    - name: Build firmware
      run: |
        source ~/esp/esp-idf-v5.4.1/export.sh
        cd tulip/esp32s3
        idf.py -DMICROPY_BOARD=TDECK build

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: tulipcc-tdeck-firmware
        path: tulip/esp32s3/build/*.bin
